# -*- coding: utf-8 -*-
"""thaicons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LvbbVkqMGuN3U2ua3UdlGJePnuKR54zi
"""

import tkinter as tk
import random

# List of Thai consonants with their names
thai_consonants = [
    ("ก", "gor gai"), ("ข", "khor khai"), ("ฃ", "khor khuad"),
    ("ค", "khor khwai"), ("ฅ", "khor khon"), ("ฆ", "khor rakhang"),
    ("ง", "ngor ngu"), ("จ", "jor jaan"), ("ฉ", "chor ching"),
    ("ช", "chor chang"), ("ซ", "sor so"), ("ฌ", "chor choe"),
    ("ญ", "yor ying"), ("ฎ", "dor cha-da"), ("ฏ", "tor pa-tak"),
    ("ฐ", "thor than"), ("ฑ", "thor montho"), ("ฒ", "thor phu-thao"),
    ("ณ", "nor nen"), ("ด", "dor dek"), ("ต", "tor tao"),
    ("ถ", "thor thung"), ("ท", "thor thahan"), ("ธ", "thor thong"),
    ("น", "nor nu"), ("บ", "bor baimai"), ("ป", "por pla"),
    ("ผ", "phor phueng"), ("ฝ", "for fa"), ("พ", "phor phan"),
    ("ฟ", "for fan"), ("ภ", "phor sam-phao"), ("ม", "mor ma"),
    ("ย", "yor yak"), ("ร", "ror rua"), ("ล", "lor ling"),
    ("ว", "wor waen"), ("ศ", "sor sala"), ("ษ", "sor rue-si"),
    ("ส", "sor suea"), ("ห", "hor hip"), ("ฬ", "lor chu-la"),
    ("อ", "or ang"), ("ฮ", "hor nok-huk")
]

class FlashcardApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Thai Consonant Flashcards")

        self.current_card = None
        self.showing_name = False

        self.card_label = tk.Label(root, text="", font=("Arial", 50), width=10, height=4, relief="ridge")
        self.card_label.pack(pady=20)

        self.flip_button = tk.Button(root, text="Flip", command=self.flip_card)
        self.flip_button.pack(pady=10)

        self.next_button = tk.Button(root, text="Next", command=self.next_card)
        self.next_button.pack(pady=10)

        self.next_card()

    def next_card(self):
        self.current_card = random.choice(thai_consonants)
        self.showing_name = False
        self.card_label.config(text=self.current_card[0])

    def flip_card(self):
        if self.current_card:
            if self.showing_name:
                self.card_label.config(text=self.current_card[0])
            else:
                self.card_label.config(text=self.current_card[1])
            self.showing_name = not self.showing_name

if __name__ == "__main__":
    root = tk.Tk()
    app = FlashcardApp(root)
    root.mainloop()